final List<String> banckList = [
  'Banreservas',
  'Banco Popular',
  'Banco BHD',
  'Banco Santa Cruz',
  'Scotiabank',
  'Banco Promerica',
  'Banco Caribe',
  'Banesco',
  'Banco BDI',
  'Banco López de Haro',
  'Banco Vimenca',
  'Banco Ademi',
  'Citibank',
  'Banco Lafise',
  'Qik Banco Digital',
  'JMMB Bank',
  'Banco Activo',
];
